# Generated by Django 4.2 on 2024-06-05 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_alter_customer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='В обработке', max_length=20)),
                ('shipping_address', models.CharField(max_length=255)),
                ('payment_status', models.CharField(choices=[('Оплачен', 'Оплачен'), ('Не оплачен', 'Не оплачен')], default='Не оплачен', max_length=11)),
                ('transaction_id', models.CharField(max_length=100)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
            ],
        ),
    ]
