# Generated by Django 4.2 on 2024-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен'), ('Ожидает отправки', 'Ожидает отправки'), ('Отправлен', 'Отправлен')], default='В обработке', max_length=20),
        ),
    ]
